name: Feature Request
description: Request a new feature
title: "[FR] Add Title Here"
body:
  - type: textarea
    id: description
    attributes:
      label: Request Description
      description: Describe the new feature you are proposing
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain how this feature would benefit users or the project
  - type: textarea
    id: proposed_implementation
    attributes:
      label: Proposed Implementation
      description: If you have initial ideas on how this feature could be implemented, please share them here
